title:        Civic Interaction
tagline:      a blog by Public Innovation
url:          http://blog.publicinnovation.org
baseurl:      /blog
author:
  name:       ""
  email:      ""
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
